### ISSUE TITLE
Metadata error with Slim 

### ISSUE THREAD

**Issue by stoplion** [patocallaghan/docpad-plugin-slim#2]
https://github.com/docpad/docpad/issues/912#issuecomment-72524348

**Comment by patocallaghan** [comment]
Apologies @stoplion. I never noticed a notification for this issue and I've just come across it now. I'll try have a gander at it over the weekend.

**Comment by patocallaghan** [comment]
@stoplion I've published a new release v2.0.1 that has support for metadata. Please note you include metadata by using `= document["title"]` rather than `@document.title` which you had in your test repo
